language: perl
sudo: false
perl:
   - "blead"       # builds perl from git
   - "dev"         # latest point release
   - "5.28"
   - "5.26"
   - "5.24"
   - "5.22"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
   - "5.8"
matrix:
  allow_failures:
    - perl: blead
    - perl: dev

before_install:
   - eval $(curl https://travis-perl.github.io/init) --perl
   - $HELPERS_ROOT/bin/cpan-config
install:
   - cpanm --notest --metacpan --skip-satisfied --with-develop --installdeps .
   - perl Makefile.PL

   # enable various test options, including parallel testing
   - export AUTOMATED_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1

   # we want these for our tests, but not for any others
   - export AUTHOR_TESTING=1
   - export RELEASE_TESTING=1
   - export PERL_AUTOINSTALL=--skip

   - make manifest

script:
   - make disttest

   # Test reverse deps (high-profile modules, taken from from Task::Catalyst):
   #  (note: currently skipping DBIC deps for speed)
   - make install

   - export AUTHOR_TESTING=0
   - export RELEASE_TESTING=0

   # pure author deps (of reverse deps):
   - cpanm --notest --metacpan --skip-satisfied YAML::Syck

   # both author deps & reverse deps:
   - cpanm --metacpan --skip-satisfied Catalyst::View::TT
   - cpanm --metacpan --skip-satisfied Catalyst::Plugin::Authentication

   # pure reverse deps (call with --test-only):
   - cpanm --test-only --metacpan -v Catalyst::Devel
   - cpanm --test-only --metacpan -v Catalyst::Action::REST
   - cpanm --test-only --metacpan -v Catalyst::Component::InstancePerContext
   - cpanm --test-only --metacpan -v Catalyst::Plugin::Session
   - cpanm --test-only --metacpan -v Catalyst::Plugin::Session::State::Cookie
   - cpanm --test-only --metacpan -v Catalyst::Plugin::Static::Simple
   - cpanm --test-only --metacpan -v Catalyst::Plugin::ConfigLoader
   #- cpanm --test-only --verbose --metacpan Catalyst::Authentication::Credential::HTTP

   # Still need to figure out why these fail in travis:
   #- cpanm --test-only --metacpan -v Catalyst::View::Email
   #- cpanm --test-only --metacpan -v Catalyst::Plugin::Session::Store::File
   #- cpanm --test-only --metacpan -v Catalyst::Plugin::I18N
